# Generated by Django 2.2.5 on 2019-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmissionNumber', models.IntegerField()),
                ('AdmissionYear', models.IntegerField()),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('BloodGroup', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('ContactDetails', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('RollNo', models.IntegerField()),
                ('Batch', models.CharField(max_length=255)),
            ],
        ),
    ]
