# Generated by Django 2.2.5 on 2019-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdmissionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
