# Generated by Django 2.2.6 on 2019-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20191010_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
