# Generated by Django 2.2.5 on 2019-09-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190926_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=255)),
                ('AuthorName', models.CharField(max_length=255)),
                ('Number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='BloodGroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
