# Generated by Django 2.2.5 on 2019-09-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190927_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Experiance', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
            ],
        ),
    ]
