# Generated by Django 2.2.6 on 2019-10-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20191010_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='duedate',
            field=models.DateField(auto_now=True),
        ),
    ]
