# Generated by Django 2.2.6 on 2019-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_fee_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
