# Generated by Django 2.2.5 on 2019-09-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(auto_now_add=True, null=True)),
                ('returndate', models.DateField(blank=True, null=True)),
                ('AdmissionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('BookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Book')),
            ],
        ),
    ]
