# Generated by Django 2.2.6 on 2019-10-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191010_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
