# Generated by Django 2.2.5 on 2019-09-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acadmeicyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyearname', models.CharField(max_length=255)),
                ('startson', models.DateField()),
                ('endson', models.DateField()),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='AdmissionNumber',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
        ),
    ]
