# Generated by Django 2.2.5 on 2019-09-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190928_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acadmeicyear',
            new_name='Academicyear',
        ),
    ]
