# Generated by Django 2.2.5 on 2019-09-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20190928_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('isactive', models.BooleanField(default=True)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Academicyear')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student')),
            ],
        ),
    ]
