# Generated by Django 2.2.6 on 2019-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
