# Generated by Django 2.2.5 on 2019-09-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Academicyear')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Course')),
            ],
        ),
    ]
