# Generated by Django 2.2.5 on 2019-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=255)),
                ('subject2', models.CharField(max_length=255)),
                ('subject3', models.CharField(max_length=255)),
                ('subject4', models.CharField(max_length=255)),
                ('subject5', models.CharField(max_length=255)),
                ('subject6', models.CharField(max_length=255)),
            ],
        ),
    ]
