# Generated by Django 2.2.6 on 2019-10-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_category_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount',
        ),
    ]
