# Generated by Django 2.2.6 on 2019-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_fee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='amount',
        ),
        migrations.AlterField(
            model_name='fee',
            name='amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
