# Generated by Django 2.2.5 on 2019-10-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
            ],
        ),
    ]
