# Generated by Django 2.2.6 on 2019-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20191017_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
