# Generated by Django 2.2.5 on 2019-10-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.periods')),
            ],
        ),
    ]
