# Generated by Django 2.2.5 on 2019-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_batch_standardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
