# Generated by Django 2.2.5 on 2019-10-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_batch_academicid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='courseid',
        ),
    ]
