# Generated by Django 2.2.5 on 2019-10-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_batch_courseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='standard',
            new_name='batchname',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='standard',
            new_name='batchname',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='endson',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='standardid',
        ),
        migrations.AddField(
            model_name='batch',
            name='academicid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.Academicyear'),
        ),
        migrations.AddField(
            model_name='batch',
            name='courseid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.Course'),
            preserve_default=False,
        ),
    ]
