# Generated by Django 2.2.5 on 2019-10-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20191001_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='academicyearname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
