# Generated by Django 2.2.5 on 2019-10-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20191002_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academicyear',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
