# Generated by Django 2.2.6 on 2019-11-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_remove_feeallocation_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeallocation',
            name='admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
            preserve_default=False,
        ),
    ]
