# Generated by Django 2.2.6 on 2019-11-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_feeallocation_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeallocation',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Student'),
        ),
    ]
