# Generated by Django 2.2.6 on 2019-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_remove_feeallocation_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
